apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: king-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: manafakingsley0@gmail.com
    privateKeySecretRef:
      name: king-secret
    solvers:
      - http01:
          ingress:
            class: nginx
