apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: king-certificate
  namespace: sock-shop
spec:
  secretName: king-secret
  issuerRef: 
    name: king-issuer
    kind: ClusterIssuer
  commonName: sock.kahmanny.pro
  dnsNames:
  - sock.kahmanny.pro
  - grafana.kahmanny.pro
  - prometheus.kahmanny.pro
